[workspace]
resolver = "3"
members = [
    "crates/*",
]
default-members = [
    "crates/mclauncher",
]

[workspace.dependencies]
cosmic-text = "0.18.2"
eframe = { version = "0.33.3", features = ["wgpu", "serde"] }
egui = { version = "0.33.3", features = ["serde"] }
serde = { version = "1.0.228", features = ["derive", "serde_derive"] }
wgpu = "28.0.0"
egui_cosmic_text = "0.2.0"


# internal crates
auth = { path = "crates/auth" }
config = { path = "crates/config" }
curseforge = { path = "crates/curseforge" }
installation = { path = "crates/installation" }
instances = { path = "crates/instances" }
modrinth = { path = "crates/modrinth" }
skinmanager = { path = "crates/skinmanager" }
worldmanager = { path = "crates/worldmanager" }
contentbrowser = { path = "crates/contentbrowser" }
modprovider = { path = "crates/modprovider" }
serverbrowser = { path = "crates/serverbrowser" }
servermanager = { path = "crates/servermanager" }
serverprotocol = { path = "crates/serverprotocol" }
egui_cosmic_glue = { path = "crates/egui_cosmic_glue" }

[profile.dev]
# Your crates (workspace members): keep normal dev behavior
opt-level = 0
debug = 2
incremental = true
codegen-units = 256

[profile.dev.package."*"]
# All dependencies (everything not in your workspace): optimize hard
opt-level = 3
debug = 1
incremental = true
codegen-units = 16
