[package]
name = "mclauncher"
version = "0.1.0"
edition = "2024"

[dependencies]
cosmic-text.workspace = true
eframe.workspace = true
egui.workspace = true
egui_cosmic_text.workspace = true
serde.workspace = true
wgpu.workspace = true
